name: pytest

on: [push] # Run the workflow on every push to the repository

jobs:
  build:

    runs-on: ubuntu-latest # Use the Ubuntu operating system for the job

    steps:
    - uses: actions/checkout@v2 # Checkout the repository code
    - name: Set up Python 3.10 # Use Python 3.10 for the job
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies # Install the project dependencies
      run: |
        python -m pip install --upgrade pip # Upgrade pip to the latest version
        pip install -r requirements.txt # Install the dependencies listed in requirements.txt
      if: fileExists('requirements.txt') # Only run this step if requirements.txt exists
    - name: Run pytest # Run pytest
      run: pytest Tests/ # This will discover and run all the tests in the tests directory
